apiVersion: apps/v1
kind: Deployment
metadata:
  name: tinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tinyproxy
  template:
    metadata:
      labels:
        app: tinyproxy
    spec:
      volumes:
      - name: proxy-config
        configMap:
          name: proxy-configmap
      containers:
      - name: squid
        image: monokal/tinyproxy:latest
        imagePullPolicy: IfNotPresent
        args: ["ANY"]
